id: I3BB824B5
legacy_id: P004569
ocr_import_info:
  bdrc_scan_id: W29257
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T21:26:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T10:20:54.639303+00:00'
last_modified: 2022-09-02 18:21:22.350383
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29257
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29257
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤཱཀྱའི་དགེ་སློང་སུ་མ་ཏི་དྷྭ་ཛ་སིངྷའི་རྟོགས་པ་བརྗོད་པ་ཉིན་མོའི་འོད།
  author: གཙོས་བསྟན་པ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.5708655578285599
  ocr_word_median_confidence_index: 0.5799999833106995
quality: null
bases:
  I5585:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5585
      total_pages: 462
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5585.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5708655578285599
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
