id: I3BB824B5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:29:48+00:00'
last_modified: '2022-06-08T02:00:20.653899+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29257
  title: ཤཱཀྱའི་དགེ་སློང་སུ་མ་ཏི་དྷྭ་ཛ་སིངྷའི་རྟོགས་པ་བརྗོད་པ་ཉིན་མོའི་འོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BD3B:
      image_group_id: I5585
      title: ''
      total_pages: 462
      order: 1
      base_file: BD3B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
