id: P004569
initial_creation_type: ocr
source_metadata:
  id: bdr:W29257
  title: ཤཱཀྱའི་དགེ་སློང་སུ་མ་ཏི་དྷྭ་ཛ་སིངྷའི་རྟོགས་པ་བརྗོད་པ་ཉིན་མོའི་འོད།
  author: ''
  volumes:
    6ed2439938684795af2576cbbd458650:
      image_group_id: I5585
      title: ''
      volume_number: 1
      total_pages: 462
